version: "3.2"
services:
  test_data_manager:
    build:
      context: ../
      dockerfile: Dockerfile.test-data-manager
      args:
        GO_BUILD_TAGS: "dev"
    logging:
      # test_data_manager's logs are too noisy
      driver: none
    environment:
      - GOOGLE_CLOUD_PROJECT=dummy-local-gcp-project
      - PORT=5200
    command:
      ["-source", "/app/test-data-manager/integration-data.yaml", "-keepAlive"]
  whatgotdone:
    build:
      context: ../
      args:
        NPM_BUILD_MODE: staging
        GO_BUILD_TAGS: staging
    environment:
      - PORT=3123
      - CSRF_SECRET_SEED=dummy-staging-seed
      - USERKIT_SECRET=dummy.dummy
      - GOOGLE_CLOUD_PROJECT=dummy-local-gcp-project
      - PUBLIC_GCS_BUCKET=whatgotdone-public-staging
    volumes:
      - ../service-account-creds-staging.json:/app/service-account-creds-staging.json
      - ./:/app/integration
  cypress:
    image: "mtlynch/cypress:8.1.0-chrome91-2"
    command: ["--browser", "chrome"]
    depends_on:
      - whatgotdone
    environment:
      - CYPRESS_baseUrl=http://whatgotdone:3123
      - CYPRESS_testDataManagerUrl=http://test_data_manager:5200
      # Uncomment the following line for verbose Cypress debugging output.
      #- DEBUG=cypress:server:request,cypress:server:server,cypress:server:proxy,cypress:network:agent,cypress:server:browsers

      # Set test timezone to Los Angeles so that we're more likely to catch
      # incorrect UTC vs. local date translations.
      - TZ=America/Los_Angeles
    working_dir: /integration
    volumes:
      - ./:/integration
